server:
  port: 8084

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres:5432/bookings_db?currentSchema=public
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092
